Repository githubschool/fri-yay, pull requests merged in 2020-03, with the labels that each got.

#18 JIRA-123 Add a descriptive caption
  _posts/0000-01-12-bradseames.md
Labels: caption

#15 JIRA-123 Add a descriptive caption
  _posts/0000-01-18-ericalloyd.md
Labels: enhancement

#17 Jira-123 Add descriptive caption
  _posts/0000-01-02-jmullini.md
Labels: enhancement

#27 Steve j utc ui editing
  _posts/0000-01-11-Stevej-utc.md
Labels: Title Change from Steve

#30 Changed the title
  _posts/0000-01-02-jmullini.md
Labels: Title Change

#34 Updated slide title
  _posts/0000-01-07-davidbroadwater.md
Labels: title-change

#29 Add a new title
  _posts/0000-01-21-ericalloyd.md
Labels: title-change

#32 Robertch ui edit
  _posts/0000-01-18-robertch1.md
Labels: Title_change
